### ISSUE TITLE
Waystones spawn too frequent

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft-reborn#12]
**Describe the bug**
I was out exploring and came across 4 waystones so close to each other I was able to get them together in a single screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/185760504-8e47bc83-db03-4f17-be53-5059f72885e1.png)

**Desktop (please complete the following information):**
 - Version 1.8

**Comment by Pingu-Pox** [comment]
Haha that's hilarious!

Reduced waystone generation rate by 1/4. Live in 1.1.12
