### ISSUE TITLE
Crash log ATLAS CRASH

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft-reborn#16]
Crash on right-click to chest 
 
 First 
[crash-2022-09-07_17.42.09-client.txt](https://github.com/Pingu-Pox/duncraft-reborn/files/9521906/crash-2022-09-07_17.42.09-client.txt)

Second
[crash-2022-09-07_18.07.55-client.txt](https://github.com/Pingu-Pox/duncraft-reborn/files/9521914/crash-2022-09-07_18.07.55-client.txt)

**Comment by Pingu-Pox** [comment]
Removed this mod
