### ISSUE TITLE
Adding a Weapon mod

### ISSUE THREAD

**Issue by ChewBaccaWakka69** [Pingu-Pox/duncraft-reborn#2]
There wasn't many weapons in the mod pack that weren't vanilla. This mod adds things like new medieval armor and many weapons like maces, axes, and new swords. Along with shields as well.

https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons

**Comment by Pingu-Pox** [comment]
Added to trello for consideration
