### ISSUE TITLE
Can't get back into game

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#27]
Went back to an area where I was clearing a few chests. There were two blocks I broke with the proper tool to collect them and the blocks disappeared. My guess is due to that fact it was in the process of DC-ing me. After that I got an exception error in the minecraft main menu screen. Not sure which one exactly. Tried to connect again and no go, same exception error popped up again. Closed down MultiMC5 completely, then reopened to try and connect again and that is when I hopped into discord to ask if server had went down. That is when Pingu informed me it did not and to restart computer. I did just that and still can not get in but this time around it gave a log, which is below.

https://paste.ee/p/qGuI9

**Comment by Pingu-Pox** [comment]
This log is likely from you restarting Duncraft, as it's just a startup log. Can you send me another log if this is still happening? (and make sure not to start Duncraft before uploading)
