### ISSUE TITLE
Little Logistics - Rail Texture

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft-reborn#29]
**Is your feature request related to a problem? Please describe.**
The rail switches added by little logistics are using vanilla minecraft base texture. This means that when used alongside the conquest textured rails it becomes a brown inconsistency 

**Describe the solution you'd like**
There are 7 rail items that need re-textured to match with base rail model.

![image](https://user-images.githubusercontent.com/97805739/196576963-b7f9a957-a426-4a7e-aa46-00e1084f7a7e.png)

**Comment by Pingu-Pox** [comment]
Open to people fixing this before I get to it.

**Comment by Pingu-Pox** [comment]
Not being fixed.
