### ISSUE TITLE
New mods to think of adding

### ISSUE THREAD

**Issue by chadica** [Pingu-Pox/duncraft-reborn#3]
Couple of mods recommendations:
Better fighting mechanic: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
Helps epic fight: https://www.curseforge.com/minecraft/mc-mods/epic-fight-nbt-integration

Cooking mechanic: https://www.curseforge.com/minecraft/mc-mods/farmers-delight

Not a cheat map mod: https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge

Custom cards: (https://www.curseforge.com/minecraft/mc-mods/buddycards
                        https://www.curseforge.com/minecraft/mc-mods/custom-cards)

Nice backpack mod: https://www.curseforge.com/minecraft/mc-mods/backpacked

More animation for the player when you look at them: https://www.curseforge.com/minecraft/mc-mods/not-enough-animations

One item in stack: https://www.curseforge.com/minecraft/mc-mods/stackone-mod

Very good magic mod : https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

Just add custom tips to the loading menu: https://www.curseforge.com/minecraft/mc-mods/tips

Geodes from the old duncraft: https://www.curseforge.com/minecraft/mc-mods/geolosys

height mod for origins: https://www.curseforge.com/minecraft/mc-mods/pehkui

Quark like the old mod in the old version: https://www.curseforge.com/minecraft/mc-mods/quark

Voice chat in game mod: https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat or
                                         https://www.curseforge.com/minecraft/mc-mods/plasmo-voice

Thirst and temperature mod: https://www.curseforge.com/minecraft/mc-mods/tough-as-nails

Revive a player when they are down: https://www.curseforge.com/minecraft/mc-mods/playerrevive

Attenuation, reverberation, and absorption through blocks: https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered

Have to answer a riddle to open a loot chest: https://www.curseforge.com/minecraft/mc-mods/riddle-chests

Bard mod: https://www.curseforge.com/minecraft/mc-mods/mimi-mod

lore about Lords  of dun: https://www.curseforge.com/minecraft/mc-mods/lore-books

Tweaks ore generation: https://www.curseforge.com/minecraft/mc-mods/ore-tweaker

**Comment by Pingu-Pox** [comment]
Closed as all mods have been added to the game/denied/added to trello for future consideration
