### ISSUE TITLE
Agricraft See Analyzer

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#30]
In the past when using this, i know you are suppose to interact with the Seed Analyzer in order to do more with seeds. I had craft it before I crafter the agricraft book so I thought maybe I wasnt able to interact with it due to that. I finally made the book and went through all the contents in it. It says to place the book on the analyzer, which I did, and then you are able to I guess use it at that point to analyze seed. So I have my book on the table, seed in right hand and I right click and nothing. I do it with an empty hand in hopes it would open up the gui and again nothing.

**Comment by Pingu-Pox** [comment]
Try this again in the next build, likely an issue with hotkeys but I am not going to go through all of yours. Ensure you do not import your options file from the previous build for 0.1.20

**Comment by Pingu-Pox** [comment]
Okay. This is intended behavior as per the developer.
See https://github.com/AgriCraft/AgriCraft/issues/1423

The functionality for server-usage is to shift-rightclick the book into the analyzer, then shift-rightclick the seed in. After that, you're free to take both out, as the book will have the updated seed information now. Sadly there is no way for me to fix this, so you're to use the workaround.
