### ISSUE TITLE
Rake not working

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#31]
Pingu restarted server around 9am I believe, or close to that time. I came back into game and went to go tend my garden. Previous made rake was missing. Could not find it anywhere and I double checked. So crafted a new one, and unable to get weeds out of crops. Rake does not work now. I made sure to click both right and left mouse to make sure I wasnt doing it wrong by chance and neither action does anything.

**Comment by Pingu-Pox** [comment]
Solved mysteriously....
