### ISSUE TITLE
Chisel & Bits missing recipes

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#36]
A few items in Chisel and bits have no craftable recipes through the gui. Items missing gui recipes are the monocle, and the pattern scanner & printer.

**Comment by Pingu-Pox** [comment]
Are we sure these aren't items meant for creative mode? I can't find any info on them on C&B's wiki. Research and let me know what their functions are.

**Comment by Pingu-Pox** [comment]
C&B has been removed from the project.
