### ISSUE TITLE
Conquest Reforge Blocks

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#37]
I noticed that the stone conquest blocks, or at least the ones I have worked with so far, break  and disappear with pickaxe. Even after being touched up with the Chisel. When most other blocks of materials that can be harvested with a pick axe would not. I was using a iron pick axe at that and was using Stone (Aka now limestone) in the stonecutter to pull out different design conquest stone blocks. Have accidentally placed them in wrong spot and go to break the block and after it breaks it disappears.

Also the wood conquest blocks can be regathered when broken with a axe. But they can not be burned. Its not a big deal, can delete if I end up not happy with a design picked and seeing it wasnt what i was exactly wanting after placing. Just felt would be nice to be able to actually use it in another fashion since it is made of wood and gathering wood from trees is a bit slow and slim. So being able to burn what would be logically usable as fuel for a furnace would be nice.

**Comment by Pingu-Pox** [comment]
Need a list of blocks and the missing harvesting types so I can look to fix this

**Comment by Pingu-Pox** [comment]
Conquest has been removed from the project.
