### ISSUE TITLE
Stuck Loading Into Spawn Village

### ISSUE THREAD

**Issue by mangafanatic** [Pingu-Pox/duncraft-reborn#38]
**Describe the bug**
Whenever I log into the Duncraft server, I get stuck loading terrain. I logged out in the spawn village.
You cannot be killed, as you are not fully on the server, and your character is stuck in an unmovable state.

**To Reproduce**
Log out in spawn village
Attempt to log in

**Expected behavior**
You begin to log in, and your screen is stuck on the "Loading Terrain" screen.

**Comment by mangafanatic** [comment]
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\sapau\OneDrive\Documents\MultiMC\instances\Düncraft Reborn 0.1.20\.minecraft\crash-reports\crash-2022-10-26_20.08.49-client.txt
java.lang.NullPointerException: Cannot invoke "net.creeperhost.ftbbackups.org.quartz.Scheduler.clear()" because "net.creeperhost.ftbbackups.FTBBackups.scheduler" is null
	at TRANSFORMER/ftbbackups2@1.0.14/net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:110)
	at java.base/java.lang.Thread.run(Thread.java:833)
AL lib: (EE) alc_cleanup: 2 devices not closed
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 26 Oct 2022 20:09:05 -0500

**Comment by Pingu-Pox** [comment]
This log is of your game starting, please ensure next time you have uploaded and copied the log's link to your clipboard before starting Düncraft again. DM me if you get "loading terrain" again
