### ISSUE TITLE
Sift till you're stiff

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft-reborn#4]
Sifted:
~~https://www.curseforge.com/minecraft/mc-mods/dietary-statistics~~
~~https://www.curseforge.com/minecraft/mc-mods/nightmareesm~~
~~https://www.curseforge.com/minecraft/mc-mods/advancement-plus~~
~~https://www.curseforge.com/minecraft/mc-mods/patchouli-datagen-ptd-lib~~
~~https://www.curseforge.com/minecraft/mc-mods/calemis-economy~~
~~https://www.curseforge.com/minecraft/mc-mods/forge-tooltip-texts-scroller~~
~~https://www.curseforge.com/minecraft/mc-mods/player-template~~
~~https://www.curseforge.com/minecraft/mc-mods/better-block-sounds~~
~~https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-croptopia~~
~~https://www.curseforge.com/minecraft/mc-mods/more-beautiful-doors~~
~~https://www.curseforge.com/minecraft/mc-mods/more-beautiful-pressure-plates~~
~~https://www.curseforge.com/minecraft/mc-mods/more-beautiful-fences-gates~~
~~https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-aurora~~
~~https://www.curseforge.com/minecraft/mc-mods/beautify-decorate~~
~~https://www.curseforge.com/minecraft/mc-mods/another-furniture~~
~~https://www.curseforge.com/minecraft/mc-mods/sheve~~
~~https://www.curseforge.com/minecraft/mc-mods/the-graveyard-biomes-forge~~
~~https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture~~
~~https://www.curseforge.com/minecraft/mc-mods/reapermod~~
~~https://www.curseforge.com/minecraft/mc-mods/milk-anything~~
~~https://www.curseforge.com/minecraft/mc-mods/australian-cattle-dogs~~
~~https://www.curseforge.com/minecraft/mc-mods/functional-fletching-table~~
~~https://www.curseforge.com/minecraft/mc-mods/underground-villages~~
~~https://www.curseforge.com/minecraft/mc-mods/difficult-raids~~
~~https://www.curseforge.com/minecraft/mc-mods/skill-cloaks~~
~~https://www.curseforge.com/minecraft/mc-mods/goat-horns-copper-horns~~
~~https://www.curseforge.com/minecraft/mc-mods/endless-ocean-aquatic-adventures~~
~~https://www.curseforge.com/minecraft/mc-mods/bed-of-nails~~
~~https://www.curseforge.com/minecraft/mc-mods/exit-confirmation~~
~~https://www.curseforge.com/minecraft/mc-mods/persona~~
~~https://www.curseforge.com/minecraft/mc-mods/runescape-weapons-and-items~~
~~https://www.curseforge.com/minecraft/mc-mods/special-drops~~
~~https://www.curseforge.com/minecraft/mc-mods/loot-goblins~~
~~https://www.curseforge.com/minecraft/mc-mods/quest-giver~~
~~https://www.curseforge.com/minecraft/mc-mods/weapon-blacksmith~~
~~https://www.curseforge.com/minecraft/mc-mods/primitive-start~~
~~https://www.curseforge.com/minecraft/mc-mods/evocation~~
~~https://www.curseforge.com/minecraft/mc-mods/rectified-slabs~~
~~https://www.curseforge.com/minecraft/mc-mods/wood-cutter~~
~~https://www.curseforge.com/minecraft/mc-mods/curious-lanterns~~
~~https://www.curseforge.com/minecraft/mc-mods/try2survive~~
~~https://www.curseforge.com/minecraft/mc-mods/getlin-ii-mod~~
~~https://www.curseforge.com/minecraft/mc-mods/ominous-darkness~~
~~https://www.curseforge.com/minecraft/mc-mods/conquests-medieval-armors-and-weapons~~
~~https://www.curseforge.com/minecraft/mc-mods/around-the-whole-world-forge~~
~~https://www.curseforge.com/minecraft/mc-mods/the-big-bench-theory-continued~~
~~https://www.curseforge.com/minecraft/mc-mods/ciif-craftable-invisible-item-frames-fabric~~
~~https://www.curseforge.com/minecraft/mc-mods/runecraft-the-barrows-brothers~~
~~https://www.curseforge.com/minecraft/mc-mods/toomany-potions~~
~~https://www.curseforge.com/minecraft/mc-mods/torch-hit~~
~~https://www.curseforge.com/minecraft/mc-mods/extra-professions~~
~~https://www.curseforge.com/minecraft/mc-mods/simplejsonvillagertrades~~
~~https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus~~
~~https://www.curseforge.com/minecraft/mc-mods/balanced-armor~~
~~https://www.curseforge.com/minecraft/mc-mods/parkour-and-more~~
~~https://www.curseforge.com/minecraft/mc-mods/sorcerycraft-dispelled~~
~~https://www.curseforge.com/minecraft/mc-mods/more-hammers-excavators~~
~~https://www.curseforge.com/minecraft/mc-mods/cosmeticarmours~~
~~https://www.curseforge.com/minecraft/mc-mods/dimensional-worldborder~~
~~https://www.curseforge.com/minecraft/mc-mods/creativekeybindtools~~
~~https://www.curseforge.com/minecraft/mc-mods/diagonalization~~
~~https://www.curseforge.com/minecraft/mc-mods/client-vein-miner~~
~~https://www.curseforge.com/minecraft/mc-mods/chunk-destroyer~~
~~https://www.curseforge.com/minecraft/mc-mods/durabuilt~~
~~https://www.curseforge.com/minecraft/mc-mods/shop-blocks-coins~~
~~https://www.curseforge.com/minecraft/mc-mods/the-extra-experience~~
~~https://www.curseforge.com/minecraft/mc-mods/better-compressed-blocks~~
~~https://www.curseforge.com/minecraft/mc-mods/top-plus~~
~~https://www.curseforge.com/minecraft/mc-mods/simple-quests-forge~~ 
~~https://www.curseforge.com/minecraft/mc-mods/stackone-mod~~
~~https://www.curseforge.com/minecraft/mc-mods/immersive-paintings~~
~~https://www.curseforge.com/minecraft/mc-mods/every-compat~~
~~https://www.curseforge.com/minecraft/mc-mods/quickplant~~
~~https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge~~
~~https://www.curseforge.com/minecraft/mc-mods/rpg-gods~~
~~https://www.curseforge.com/minecraft/mc-mods/no-more-inifinite-water~~

**Comment by Pingu-Pox** [comment]
Sifted
