### ISSUE TITLE
No life after death

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/duncraft-reborn#40]
**Screenshots**
![image](https://user-images.githubusercontent.com/102630179/183275210-9817dc5e-a354-4124-8fa7-40d5b3ef5d6c.png)

After dying you can not hit the respawn button, after going to the title screen and return, you still cant hit the respawn button.

**Comment by JohannesRamheart** [comment]
After multimc restart you still cant hit the respawn button
Neither can agrem

**Comment by Pingu-Pox** [comment]
Was related to experimental mods at the start of this pack's development. Has since been fixed by removing the offending mod.
