### ISSUE TITLE
Biome Mods

### ISSUE THREAD

**Issue by ChewBaccaWakka69** [Pingu-Pox/duncraft-reborn#6]
Here are a few biome mods. Ya'll were talking about how the world would have to be reset when ya'll find one and didn't really see the point in playing super far into a world if we were going to have to reset it so heres a few biome mods that are pretty nice. Then a few other aswell lol

Biome Mod
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
https://www.curseforge.com/minecraft/mc-mods/terraforged

Seasons Mod
https://www.curseforge.com/minecraft/mc-mods/serene-seasons

Pretty Mods
https://www.curseforge.com/minecraft/mc-mods/dynamictrees
(If not compatible with biomes there is a specific one that is compatible with biomes of plenty)
https://www.curseforge.com/minecraft/mc-mods/dtbop

**Comment by Pingu-Pox** [comment]
Downloaded and will test.
